#!/usr/bin/env python3
import argparse
import csv
import json
import math
from datetime import datetime
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(
        description="Fit a linear depth correction model from oak_wheelchair_depth_test capture log (CSV or JSON)"
    )
    parser.add_argument(
        "--log-file",
        default="/tmp/oak-wheelchair-depth-test/capture_log.json",
        help="Capture log file generated by oak_wheelchair_depth_test (.csv or .json)",
    )
    parser.add_argument(
        "--output",
        default="/tmp/oak-wheelchair-depth-test/depth_linear_calibration.json",
        help="Output calibration JSON path",
    )
    return parser.parse_args()


def load_csv_samples(log_file: Path):
    samples = []
    with log_file.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            raw = (row.get("raw_depth_mm") or "").strip()
            actual = (row.get("actual_distance_mm") or "").strip()
            if not raw or not actual:
                continue
            try:
                raw_v = float(raw)
                actual_v = float(actual)
            except ValueError:
                continue
            samples.append((raw_v, actual_v, row))
    return samples


def load_json_samples(log_file: Path):
    samples = []
    payload = json.loads(log_file.read_text(encoding="utf-8"))
    if not isinstance(payload, list):
        raise SystemExit("JSON log file must contain an array.")

    for row in payload:
        if not isinstance(row, dict):
            continue
        raw = row.get("raw_depth_mm")
        actual = row.get("actual_distance_mm")
        if raw in (None, "") or actual in (None, ""):
            continue
        try:
            raw_v = float(raw)
            actual_v = float(actual)
        except (TypeError, ValueError):
            continue
        samples.append((raw_v, actual_v, row))
    return samples


def load_samples(log_file: Path):
    if log_file.suffix.lower() == ".json":
        return load_json_samples(log_file)
    return load_csv_samples(log_file)


def fit_linear(samples):
    xs = [x for x, _, _ in samples]
    ys = [y for _, y, _ in samples]
    n = len(xs)
    mean_x = sum(xs) / n
    mean_y = sum(ys) / n

    var_x = sum((x - mean_x) ** 2 for x in xs)
    if var_x == 0:
        raise SystemExit("Cannot fit linear model: raw_depth_mm values are constant.")

    cov_xy = sum((x - mean_x) * (y - mean_y) for x, y in zip(xs, ys))
    slope = cov_xy / var_x
    intercept = mean_y - slope * mean_x

    ss_tot = sum((y - mean_y) ** 2 for y in ys)
    ss_res = sum((y - (slope * x + intercept)) ** 2 for x, y in zip(xs, ys))
    r_squared = 1.0 if ss_tot == 0 else 1.0 - (ss_res / ss_tot)

    mae = sum(abs(y - (slope * x + intercept)) for x, y in zip(xs, ys)) / n
    rmse = math.sqrt(sum((y - (slope * x + intercept)) ** 2 for x, y in zip(xs, ys)) / n)
    return slope, intercept, r_squared, mae, rmse


def main():
    args = parse_args()
    log_file = Path(args.log_file)
    output = Path(args.output)

    if not log_file.exists():
        raise SystemExit(f"log file not found: {log_file}")

    samples = load_samples(log_file)
    if len(samples) < 2:
        raise SystemExit("Need at least 2 rows with both raw_depth_mm and actual_distance_mm filled.")

    slope, intercept, r_squared, mae, rmse = fit_linear(samples)
    payload = {
        "model_type": "linear_depth_correction",
        "enabled": True,
        "slope": slope,
        "intercept": intercept,
        "sample_count": len(samples),
        "r_squared": r_squared,
        "mae_mm": mae,
        "rmse_mm": rmse,
        "input_log_file": str(log_file),
        "generated_at": datetime.now().isoformat(timespec="seconds"),
    }

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(f"saved calibration: {output}")
    print(f"sample_count={len(samples)}")
    print(f"slope={slope:.6f}")
    print(f"intercept={intercept:.6f}")
    print(f"r_squared={r_squared:.6f}")
    print(f"mae_mm={mae:.2f}")
    print(f"rmse_mm={rmse:.2f}")


if __name__ == "__main__":
    main()
